language: node_js

node_js:
  - "8"
  - "10"

cache:
  directories:
    - "node_modules"

env:
  - SCRIPT_ID=ple
  - SCRIPT_ID=jrdb
  - SCRIPT_ID=iv

script:
  - npm run build -- --script=$SCRIPT_ID

email:
  on_success: never
  on_failure: always